# Generated by Django 4.0.4 on 2022-04-29 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_candidatesapplied'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesapplied',
            name='appliedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatesapplied',
            name='resume',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
